import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Type-aware linting (catches unsafe `any` propagation that the plain
  // syntactic `recommended` ruleset above cannot see) for first-party
  // TypeScript source — scoped to exactly the files tsconfig.json includes,
  // since every file under these type-checked rules must resolve to a
  // program via the TS project service.
  {
    files: ["**/*.{ts,tsx,mts}"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
  // Plain JS config files (this file included) aren't part of
  // tsconfig.json's `include` and carry no type information — disable the
  // type-checked rules for them rather than trying to force them into the
  // TS project service.
  {
    files: ["**/*.{js,mjs,cjs}"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  // Deno Edge Function entrypoints (supabase/functions/**/index.ts) run in
  // Deno, not Node — they use the `Deno` global and `npm:`/relative-.ts
  // imports that tsconfig.json deliberately excludes (see its `exclude`).
  // parser.ts/parser.test.ts under the same directories stay fully
  // type-checked and lint-checked; only the Deno-specific entrypoints and
  // the cross-function `_shared` helpers need this carve-out.
  {
    files: ["supabase/functions/**/index.ts", "supabase/functions/_shared/**"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  // Disables ESLint stylistic rules that would conflict with Prettier.
  // Formatting itself is Prettier's job (`pnpm format` / `pnpm format:check`).
  prettierConfig,
  {
    rules: {
      // Standard convention: a leading underscore marks an intentionally
      // unused binding (e.g. a destructured-out field, a mock's unused
      // parameter) without disabling the check entirely.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Supabase CLI local/runtime artifacts:
    "supabase/.temp/**",
    // Coverage output:
    "coverage/**",
    // Supabase CLI-generated database types — regenerated by
    // `pnpm db:types:local` / `pnpm db:types:linked`, never hand-edited.
    "src/types/database.types.ts",
  ]),
]);

export default eslintConfig;
